In [1]:
import faiss
import pickle

In [2]:
with open('embeddings/authors_0.pkl', 'rb') as f:
    data2 = pickle.load(f)

In [5]:
data2.keys()

dict_keys([72834, 41026, 10392, 113098])

In [13]:
dim = 512
k = 10  # количество “командиров”
quantiser = faiss.IndexFlatL2(dim) 
index = faiss.IndexIVFFlat(quantiser, dim, k)
vectors = np.random.random((100, dim)).astype('float32')  # 1 000 000 “воинов”

In [14]:
index = faiss.index_factory(dim, "IVF10,Flat")
print(index.is_trained)   # False.
index.train(vectors)  # Train на нашем наборе векторов
 
# Обучение завершено, но векторов в индексе пока нет, так что добавляем их в индекс:
print(index.is_trained)  # True
print(index.ntotal)   # 0
index.add(vectors)
print(index.ntotal)   # 1000000

False


WARNING clustering 100 points to 10 centroids: please provide at least 390 training points


True
0
100


In [4]:
topn = 7
D, I = index.search(vectors[:5], topn)  # Возвращает результат: Distances, Indices
print(I)
print(D)

[[   0 5662 6778 7738 6931 7809 7184]
 [   1 5831 8039 2150 5426 4569 6325]
 [   2 7348 2476 2048 5091 6322 3617]
 [   3  791 3173 6323 8374 7273 5842]
 [   4 6236 7548  746 6144 3906 5455]]
[[ 0.       71.5358   72.18826  72.74326  73.22424  73.333275 73.73315 ]
 [ 0.       67.604836 68.49479  68.842224 71.83992  72.084335 72.108154]
 [ 0.       66.717865 67.72709  69.63664  70.359055 70.93329  71.03238 ]
 [ 0.       68.2641   68.32059  68.82381  68.86326  69.12085  69.55176 ]
 [ 0.       72.03398  72.32419  73.00312  73.13061  73.76176  73.81279 ]]
